//Maya ASCII 2017ff05 scene
//Name: seed2_shd_v001.ma
//Last modified: Fri, Jul 19, 2019 04:12:47 PM
//Codeset: 1252
requires maya "2017ff05";
requires -nodeType "RedshiftBumpMap" -nodeType "RedshiftMaterial" "redshift4maya" "2.6.32";
requires "stereoCamera" "10.0";
requires "pydata" "0.4";
requires "tickle" "2.80";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2017";
fileInfo "version" "2017";
fileInfo "cutIdentifier" "201710312130-1018716";
fileInfo "osv" "Microsoft Windows 8 Business Edition, 64-bit  (Build 9200)\n";
fileInfo "license" "education";
createNode RedshiftMaterial -n "shd_eye";
	rename -uid "C0CFF9BE-4C41-AF03-B912-73B065E46537";
	setAttr ".v" 1;
	setAttr ".refl_roughness" 0.30000001192092896;
	setAttr ".refl_brdf" 1;
	setAttr ".ms_amount" 1;
	setAttr ".ms_mode" 1;
	setAttr ".coat_weight" 1;
	setAttr ".coat_roughness" 0.10000000149011612;
	setAttr ".coat_brdf" 1;
createNode RedshiftMaterial -n "shd_seed2";
	rename -uid "E2B858A2-4770-F9C0-9724-D59F2D2F305C";
	setAttr ".v" 1;
	setAttr ".ms_amount" 1;
	setAttr ".ms_radius_scale" 0.5;
	setAttr ".ms_mode" 1;
	setAttr ".ms_weight0" 0.5;
	setAttr ".ms_radius0" 0.80000001192092896;
	setAttr ".ms_color1" -type "float3" 0.91329998 0.2085 0.1186 ;
	setAttr ".ms_weight1" 0.5;
	setAttr ".ms_radius1" 2;
createNode shadingEngine -n "rsMaterial4SG";
	rename -uid "592AC41C-4061-E6F0-2FFC-7EB3B66D3A52";
	setAttr ".ihi" 0;
	setAttr -s 3 ".dsm";
	setAttr ".ro" yes;
createNode place2dTexture -n "place2dTexture2";
	rename -uid "E004D5C7-487A-2C9B-C2DD-4297D682D724";
createNode place2dTexture -n "place2dTexture3";
	rename -uid "4AE2DD3A-4992-925E-8475-C29C444EE288";
createNode RedshiftBumpMap -n "rsBumpMap1";
	rename -uid "42D3C70A-43FA-37AA-D077-EEB3C378D09E";
	setAttr ".inputType" 1;
	setAttr ".scale" 1;
	setAttr ".flipY" yes;
createNode place2dTexture -n "place2dTexture1";
	rename -uid "5EDED935-42B0-429F-6A9B-E29373FB2F08";
createNode file -n "file3";
	rename -uid "3A09280D-4481-B27E-EB3A-E2AE5BE6C0B7";
	setAttr ".ftn" -type "string" "P:/library/bank/bank_CS/chars/seed2/maya//sourceimages/assets/chars/seed2/seed2_roughness.1001.png";
	setAttr ".ft" 0;
	setAttr ".uvt" 3;
	setAttr ".cs" -type "string" "Raw";
createNode file -n "file1";
	rename -uid "5710CED8-45A7-F001-1773-76ACD8B011E4";
	setAttr ".ftn" -type "string" "P:/library/bank/bank_CS/chars/seed2/maya//sourceimages/assets/chars/seed2/seed2_diffuse.1001.png";
	setAttr ".ft" 0;
	setAttr ".uvt" 3;
	setAttr ".cs" -type "string" "sRGB";
createNode shadingEngine -n "rsMaterial1SG";
	rename -uid "DF7D91A5-405E-DA88-2F14-289A42F5A932";
	setAttr ".ihi" 0;
	setAttr -s 10 ".dsm";
	setAttr ".ro" yes;
createNode file -n "file2";
	rename -uid "E272E85E-4865-B09A-F637-EDA59EA8B7F9";
	setAttr ".ftn" -type "string" "P:/library/bank/bank_CS/chars/seed2/maya//sourceimages/assets/chars/seed2/seed2_normal.1001.png";
	setAttr ".uvt" 3;
	setAttr ".cs" -type "string" "Raw";
createNode materialInfo -n "materialInfo5";
	rename -uid "FD14CDD9-49F8-F613-5955-A2A54925F3BE";
createNode materialInfo -n "materialInfo1";
	rename -uid "853B168B-4F60-64CC-32B0-0DA22F4C34B5";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "37B57AFB-48FB-6195-1A69-5E8430189AA0";
	setAttr -s 8 ".lnk";
	setAttr -s 8 ".slnk";
select -ne :time1;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".o" 1;
	setAttr -av ".unw" 1;
	setAttr -k on ".etw";
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 4 ".st";
	setAttr -cb on ".an";
	setAttr -cb on ".pt";
select -ne :renderGlobalsList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
select -ne :defaultShaderList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 6 ".s";
select -ne :postProcessList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 146 ".u";
select -ne :defaultRenderingList1;
	setAttr -s 3 ".r";
select -ne :defaultTextureList1;
	setAttr -s 4 ".tx";
select -ne :initialShadingGroup;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 10 ".dsm";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
select -ne :initialParticleSE;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "redshift";
	setAttr ".outf" 51;
	setAttr ".imfkey" -type "string" "exr";
	setAttr ".pff" yes;
select -ne :defaultResolution;
	setAttr -av -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -k on ".bnm";
	setAttr -av -k on ".w" 1800;
	setAttr -av -k on ".h" 3000;
	setAttr -av -k on ".pa" 1;
	setAttr -av -k on ".al" yes;
	setAttr -av -k on ".dar" 0.60000002384185791;
	setAttr -av -k on ".ldar";
	setAttr -k on ".dpi";
	setAttr -av -k on ".off";
	setAttr -av -k on ".fld";
	setAttr -av -k on ".zsl";
	setAttr -k on ".isu";
	setAttr -k on ".pdu";
select -ne :hardwareRenderGlobals;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k off ".ctrs" 256;
	setAttr -av -k off ".btrs" 512;
	setAttr -k off ".fbfm";
	setAttr -k off -cb on ".ehql";
	setAttr -k off -cb on ".eams";
	setAttr -k off -cb on ".eeaa";
	setAttr -k off -cb on ".engm";
	setAttr -k off -cb on ".mes";
	setAttr -k off -cb on ".emb";
	setAttr -av -k off -cb on ".mbbf";
	setAttr -k off -cb on ".mbs";
	setAttr -k off -cb on ".trm";
	setAttr -k off -cb on ".tshc";
	setAttr -k off ".enpt";
	setAttr -k off -cb on ".clmt";
	setAttr -k off -cb on ".tcov";
	setAttr -k off -cb on ".lith";
	setAttr -k off -cb on ".sobc";
	setAttr -k off -cb on ".cuth";
	setAttr -k off -cb on ".hgcd";
	setAttr -k off -cb on ".hgci";
	setAttr -k off -cb on ".mgcs";
	setAttr -k off -cb on ".twa";
	setAttr -k off -cb on ".twz";
	setAttr -k on ".hwcc";
	setAttr -k on ".hwdp";
	setAttr -k on ".hwql";
	setAttr -k on ".hwfr";
	setAttr -k on ".soll";
	setAttr -k on ".sosl";
	setAttr -k on ".bswa";
	setAttr -k on ".shml";
	setAttr -k on ".hwel";
select -ne :ikSystem;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -k on ".bnm";
	setAttr -av -k on ".gsn";
	setAttr -k on ".gsv";
	setAttr -s 2 ".sol";
connectAttr "file1.oc" "shd_eye.diffuse_color";
connectAttr "rsBumpMap1.oc" "shd_eye.bump_input";
connectAttr "file1.oc" "shd_seed2.diffuse_color";
connectAttr "rsBumpMap1.oc" "shd_seed2.bump_input";
connectAttr "file3.ocr" "shd_seed2.refl_roughness";
connectAttr "msh_eye_LShape.iog" "rsMaterial4SG.dsm" -na;
connectAttr "msh_eye_RShape.iog" "rsMaterial4SG.dsm" -na;
connectAttr "shd_eye.oc" "rsMaterial4SG.ss";
connectAttr "file2.oc" "rsBumpMap1.input";
connectAttr ":defaultColorMgtGlobals.cme" "file3.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file3.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file3.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file3.ws";
connectAttr "place2dTexture3.c" "file3.c";
connectAttr "place2dTexture3.tf" "file3.tf";
connectAttr "place2dTexture3.rf" "file3.rf";
connectAttr "place2dTexture3.mu" "file3.mu";
connectAttr "place2dTexture3.mv" "file3.mv";
connectAttr "place2dTexture3.s" "file3.s";
connectAttr "place2dTexture3.wu" "file3.wu";
connectAttr "place2dTexture3.wv" "file3.wv";
connectAttr "place2dTexture3.re" "file3.re";
connectAttr "place2dTexture3.of" "file3.of";
connectAttr "place2dTexture3.r" "file3.ro";
connectAttr "place2dTexture3.n" "file3.n";
connectAttr "place2dTexture3.vt1" "file3.vt1";
connectAttr "place2dTexture3.vt2" "file3.vt2";
connectAttr "place2dTexture3.vt3" "file3.vt3";
connectAttr "place2dTexture3.vc1" "file3.vc1";
connectAttr "place2dTexture3.o" "file3.uv";
connectAttr "place2dTexture3.ofs" "file3.fs";
connectAttr ":defaultColorMgtGlobals.cme" "file1.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file1.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file1.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file1.ws";
connectAttr "place2dTexture1.c" "file1.c";
connectAttr "place2dTexture1.tf" "file1.tf";
connectAttr "place2dTexture1.rf" "file1.rf";
connectAttr "place2dTexture1.mu" "file1.mu";
connectAttr "place2dTexture1.mv" "file1.mv";
connectAttr "place2dTexture1.s" "file1.s";
connectAttr "place2dTexture1.wu" "file1.wu";
connectAttr "place2dTexture1.wv" "file1.wv";
connectAttr "place2dTexture1.re" "file1.re";
connectAttr "place2dTexture1.of" "file1.of";
connectAttr "place2dTexture1.r" "file1.ro";
connectAttr "place2dTexture1.n" "file1.n";
connectAttr "place2dTexture1.vt1" "file1.vt1";
connectAttr "place2dTexture1.vt2" "file1.vt2";
connectAttr "place2dTexture1.vt3" "file1.vt3";
connectAttr "place2dTexture1.vc1" "file1.vc1";
connectAttr "place2dTexture1.o" "file1.uv";
connectAttr "place2dTexture1.ofs" "file1.fs";
connectAttr "msh_bodyShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_leafShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_pupil_LShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_pupil_RShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_stemShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_gumUpShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_gumDnShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_teethUpShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_teethDnShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "msh_tongueShape.iog" "rsMaterial1SG.dsm" -na;
connectAttr "shd_seed2.oc" "rsMaterial1SG.ss";
connectAttr ":defaultColorMgtGlobals.cme" "file2.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "file2.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "file2.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "file2.ws";
connectAttr "place2dTexture2.c" "file2.c";
connectAttr "place2dTexture2.tf" "file2.tf";
connectAttr "place2dTexture2.rf" "file2.rf";
connectAttr "place2dTexture2.mu" "file2.mu";
connectAttr "place2dTexture2.mv" "file2.mv";
connectAttr "place2dTexture2.s" "file2.s";
connectAttr "place2dTexture2.wu" "file2.wu";
connectAttr "place2dTexture2.wv" "file2.wv";
connectAttr "place2dTexture2.re" "file2.re";
connectAttr "place2dTexture2.of" "file2.of";
connectAttr "place2dTexture2.r" "file2.ro";
connectAttr "place2dTexture2.n" "file2.n";
connectAttr "place2dTexture2.vt1" "file2.vt1";
connectAttr "place2dTexture2.vt2" "file2.vt2";
connectAttr "place2dTexture2.vt3" "file2.vt3";
connectAttr "place2dTexture2.vc1" "file2.vc1";
connectAttr "place2dTexture2.o" "file2.uv";
connectAttr "place2dTexture2.ofs" "file2.fs";
connectAttr "rsMaterial4SG.msg" "materialInfo5.sg";
connectAttr "shd_eye.msg" "materialInfo5.m";
connectAttr "rsMaterial1SG.msg" "materialInfo1.sg";
connectAttr "shd_seed2.msg" "materialInfo1.m";
connectAttr "file1.msg" "materialInfo1.t" -na;
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "rsMaterial1SG.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "rsMaterial4SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "rsMaterial1SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "rsMaterial4SG.message" ":defaultLightSet.message";
connectAttr "rsMaterial1SG.pa" ":renderPartition.st" -na;
connectAttr "rsMaterial4SG.pa" ":renderPartition.st" -na;
connectAttr "shd_seed2.msg" ":defaultShaderList1.s" -na;
connectAttr "shd_eye.msg" ":defaultShaderList1.s" -na;
connectAttr "place2dTexture1.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture2.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture3.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "file1.msg" ":defaultTextureList1.tx" -na;
connectAttr "file2.msg" ":defaultTextureList1.tx" -na;
connectAttr "rsBumpMap1.msg" ":defaultTextureList1.tx" -na;
connectAttr "file3.msg" ":defaultTextureList1.tx" -na;
// End of seed2_shd_v001.ma
